[project]
name = 'lamp_contract'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.delegate_withdrawal_wallet]
path = 'contracts/delegate_withdrawal_wallet.clar'
clarity_version = 2
epoch = 2.5

[contracts.file_backup]
path = 'contracts/file_backup.clar'
clarity_version = 2
epoch = 2.5

[contracts.garage_with_value_increment_limits]
path = 'contracts/garage_with_value_increment_limits.clar'
clarity_version = 2
epoch = 2.5

[contracts.user_ID]
path = 'contracts/user_ID.clar'
clarity_version = 2
epoch = 2.5

[contracts.vote_expiry]
path = 'contracts/vote_expiry.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
